apiVersion: v1
kind: Service
metadata:
  name: knowledge-repo-server
  namespace: knowledge-repo
spec:
  type: NodePort
  selector:
    app: knowledge-repo-server
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30050